# Generated by Django 4.2.3 on 2023-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='newimage',
            field=models.CharField(default='New image', max_length=100),
        ),
    ]
