# Generated by Django 4.2.3 on 2023-08-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_uploadimage_newimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.RemoveField(
            model_name='item',
            name='details',
        ),
        migrations.RemoveField(
            model_name='item',
            name='distributor',
        ),
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.ForeignKey(blank=True, default='5', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rate'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
